openapi: 3.0.3
info:
  title: Bookstore API
  version: 1.0.0
  description: An API for managing books, authors, and genres in a bookstore.

paths:
  /books:
    get:
      summary: Get a list of books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Create a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

  /authors:
    get:
      summary: Get a list of authors
      responses:
        '200':
          description: A list of authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
    post:
      summary: Create a new author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '201':
          description: Author created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'

components:
  schemas:
    Book:
      type: object
      properties:
        title:
          type: string
        author:
          $ref: '#/components/schemas/Author'
        ISBN:
          type: string
        publicationDate:
          type: string
          format: date
        genre:
          type: array
          items:
            $ref: '#/components/schemas/Genre'
        description:
          type: string
        coverImageURL:
          type: string
        numberOfPages:
          type: integer

    Author:
      type: object
      properties:
        name:
          type: string
        birthDate:
          type: string
          format: date
        nationality:
          type: string
        biography:
          type: string

    Genre:
      type: object
      properties:
        name:
          type: string
