spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    denisjulio.bookstoreapi: debug